### ISSUE TITLE
Problems with "module" special dependency

### ISSUE THREAD

**Issue by sprat** [gfranko/amdclean#104]
I've found some problems when trying to the `module` special dependency in order to access the `module.config()`.

1. Module configs variable name clash

Here is an example:
```javascript
define(['module'], function (module) {
    'use strict';

    return {
        config: module.config()
    };
});
```

This code is converted to:

```javascript
var modular4, module = {
    'modular4': {
      'config': function () {
        return { ... };
      }
    }
  };
modular4 = function (module) {
  'use strict';
  return { config: module.config() };
}(module['modular4']);
window.modular4 = modular4;
```

The module configs are stored in a `module` variable. It's a pretty bad variable name, as it can break shimmed modules included in the same file. In fact, many libraries have a universal module definition in top of them so that the same code can work in node (CJS) and in the browser (AMD), and they often test the availability of a `module` variable to detect the module format.

I would suggest renaming this variable to something else... maybe `moduleConfigs`. Another idea would be to store the configs of each module in the module's variable itself, as in this example:
```javascript
var modular4 = {
      'config': function () {
        return { ... };
      }
    }
  };
modular4 = function (module) {
  'use strict';
  return { config: module.config() };
}(modular4);
window.modular4 = modular4;
```

2. Wrapped CJS modules are completely broken

As an example:
```javascript
define(function (require, exports, module) {
    'use strict';

    var config = module.config();

    exports.config = config;
});
```

The code above is converted to:
```javascript
var modular1 = {}, module = {
    'modular1': {
      'config': function () {
        return { ... };
      }
    }
  };
modular1 = function (exports) {
  'use strict';
  var config = module.config();
  exports.config = config;
  return exports;
}({}, {}, module['modular1']);
window.modular1 = modular1;
```
This is obviously wrong.

I can probably submit a pull request solving the first point. The second one is more tricky, I'm not sure I can solve the problem by myself.

**Comment by sprat** [comment]
Ok, I just made a pull request solving problem 1. Note that I chose the "modules" variable name instead of "moduleConfig", because, I think we can solve #92 by putting all the modules exports in this object instead of declaring one (global) variable per AMD module.

**Comment by sprat** [comment]
I think the problem is due to the blacklisting of 'module' dependency', so I propose to generate CJS modules like this:

```javascript
var amd_modules={
  'my_module': {
    exports: {}
    config: function() {
      return { /*...*/ };
    }
  }
};
amd_modules['my_module'] = function (exports, module) {
  /* ... no transforms of module/exports here */
  return exports;
}(amd_modules['my_module'].exports, amd_modules['my_module']);
```

If we agree on the output format, I can give it a try.

**Comment by gfranko** [comment]
You can use the `prefixTransform` option to prefix your variables how you like.
