### ISSUE TITLE
bin/amdclean

### ISSUE THREAD

**Issue by rejeep** [gfranko/amdclean#107]
Hi,

Is there any reason there is no `bin/amdclean` so that you for example can do the below?

``` shell
$ amdclean --config amdclean.config.json dist/main.js > dist/main.clean.js
```

If you think such a command would be useful, I'm willing to contribute.

**Comment by TechQuery** [comment]
After failed with [the offical r.js example](https://github.com/gfranko/amdclean#amdclean-with-the-requirejs-optimizer), I wrote [a command-line script](https://github.com/TechQuery/iQuery.js/blob/56838acab3ce966aca34e1935a0760be0d48b715/build/clean.js) to process `stdout` of r.js.

Hope to help you~
