### ISSUE TITLE
The variable conflict logic in v2.4.0 and onwards

### ISSUE THREAD

**Issue by thekot** [gfranko/amdclean#109]
I've just updated from v2.3.0 to latest and found that something went wrong with my project. I find out that it's because of 4725a2a which disscussed in #57

In my project I'm using [store2](https://github.com/nbubna/store/blob/master/src/store2.js) library which have code as follow

    ;(function() {
        var store = 'Something';
    
        if (typeof define === 'function' && define.amd !== undefined) {
            define(function () {
                return store;
            });
        }
    })();

Which amdclean v2.4.0 translates to

    var store;
    (function () {
      var store = 'Something';
      if (true) {
        store = function () {
          return store;
        }();
      }
    }());

So outer `store` variable left undefined.

Could you help me to fix that?

**Comment by sprat** [comment]
See https://github.com/gfranko/amdclean/issues/92

**Comment by gfranko** [comment]
You should be able to use the `prefixTransform` option to change the module name of **store** to something else
