### ISSUE TITLE
Problem with jQuery

### ISSUE THREAD

**Issue by tybenz** [gfranko/amdclean#25]
I'm using jQuery 1.9.1 with bower and when I compile with amdclean, I'm getting undefined error: "jquery" (note: lowercase).

If I tweak my build script to find and replace "jquery" -> "jQuery" everything works fine.

This is my build config:

``` javascript
({
  baseUrl: '../src',

  out: '../lego.min.js',
  // optimize: 'uglify2',

  include: [ 'namespace' ],
  // Remove license comments for almond, jquery, etc
  preserveLicenseComments: false,

  paths: {
    'jquery': '../bower_components/jquery/jquery'
  },

  onBuildWrite: function (moduleName, path, contents) {
    return module.require('amdclean').clean(contents);
  }
})
```

**Comment by vasvi** [comment]
Hi, I am trying to build libraries that contain third-party dependencies using the hack described by @gfranko above in one of the comments,  I am a little confused over to where to Set the third-party dependency local variable values inside  source code. Has anybody implemented this way?
