### ISSUE TITLE
AMDclean does not clean invocations of AMD

### ISSUE THREAD

**Issue by Juice10** [gfranko/amdclean#78]
In this example http://gregfranko.com/amdclean/?code=define('example'%2C%20%5B%5D%2C%20function()%20%7B%0A%20%20return%20'Convert%20AMD%20code%20to%20standard%20JavaScript'%3B%0A%7D)%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%0Adefine(%5B'example'%5D%2C%20function(x)%7B%0A%20%20console.log(x)%0A%7D)
AMD:
```javascript
define('example', [], function() {
  return 'Convert AMD code to standard JavaScript';
});
            
define(['example'], function(x){
  console.log(x)
})
```
Cleaned Javascript
```javascript
;(function() {
var example;
example = 'Convert AMD code to standard JavaScript';
define(['example'], function (x) {
  console.log(x);
});
}());
```

 AMDclean does not remove AMD the from following code:
```javascript
define(['example'], function(x){
  console.log(x)
})
```
Shouldn't that be something like?
```javascript
(function(x){
  console.log(x)
})(example)
```

**Comment by gfranko** [comment]
The reason AMDclean doesn't clean that AMD module is because there is no module ID that is passed to it (Usually the Require.js optimizer handles this)
