### ISSUE TITLE
doc: Question about browserify con

### ISSUE THREAD

**Issue by chrisdickinson** [gfranko/amdclean#82]
> Adds boilerplate code to files (increasing file size and decreasing code readability)

What boilerplate does browserify require in one's code?

**Comment by gfranko** [comment]
Check the first line of this [example](https://raw.githubusercontent.com/thlorenz/browserify-markdown-editor/master/bundle.js)

**Comment by chrisdickinson** [comment]
Ah! That makes sense. I was thinking in terms of "per-source-file" boilerplate, not in generated output. Thanks.
