### ISSUE TITLE
removeUseStricts doesn't work

### ISSUE THREAD

**Issue by lukeapage** [gfranko/amdclean#87]
The following code - 
https://github.com/gfranko/amdclean/blob/master/src/amdclean.js#L572
doesn't assign the result of the filter expression back. If I add this line afterwards, it starts working
```
callbackFunc.body.body = body;
```

I had thought the opposite  - that removeUseStricts was always true, but that was down to requirejs' useStrict option.

**Comment by gfranko** [comment]
This has been merged and released with **2.5.0**.  Thank you!
